# Generated by Django 4.0.4 on 2022-05-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areas',
            old_name='area_name',
            new_name='text',
        ),
    ]
