# Generated by Django 4.0.4 on 2022-05-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses_app', '0002_rename_area_name_areas_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areas',
            old_name='text',
            new_name='area_name',
        ),
    ]
