# Generated by Django 4.0.4 on 2022-06-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses_app', '0002_remove_comments_texttt_places_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='file',
            new_name='post_image',
        ),
    ]
