# Generated by Django 4.0.4 on 2022-05-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses_app', '0004_places'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name_plural': 'places'},
        ),
        migrations.RenameField(
            model_name='areas',
            old_name='area_name',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='place',
            new_name='area',
        ),
    ]
